name: Deploy to Firebase Hosting on Push and PR
 
# ▼▼▼【修正点1】ワークフローに権限を与える ▼▼▼
permissions:
  checks: write
  contents: read
  pull-requests: write
 
on:
  push:
    branches:
      - main
  pull_request:
 
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # ▼▼▼【修正点2】最新版のアクションを利用する ▼▼▼
      - uses: actions/checkout@v4
 
      # Flutterの実行環境を準備
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
 
      - name: Build Flutter web app
        run: flutter build web
 
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_HOGE_695BF }}
          projectId: hoge-695bf